create table if not exists public.driver_availability_slots (
  id bigint generated by default as identity primary key,
  driver_id uuid references public.profiles(id) not null,
  day_of_week int not null check (day_of_week between 0 and 6),
  start_min int not null check (start_min between 0 and 1439),
  end_min int not null check (end_min between 1 and 1440 and end_min > start_min),
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.driver_availability_slots enable row level security;

grant select, insert, update, delete on public.driver_availability_slots to authenticated;
grant usage, select on sequence public.driver_availability_slots_id_seq to authenticated;

drop policy if exists "Drivers can view own availability slots" on public.driver_availability_slots;
drop policy if exists "Drivers can insert own availability slots" on public.driver_availability_slots;
drop policy if exists "Drivers can update own availability slots" on public.driver_availability_slots;
drop policy if exists "Drivers can delete own availability slots" on public.driver_availability_slots;
drop policy if exists "Admins can view all availability slots" on public.driver_availability_slots;

create policy "Drivers can view own availability slots" on public.driver_availability_slots for select
using (
  driver_id = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'driver'
  )
);

create policy "Drivers can insert own availability slots" on public.driver_availability_slots for insert
with check (
  driver_id = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'driver'
  )
);

create policy "Drivers can update own availability slots" on public.driver_availability_slots for update
using (
  driver_id = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'driver'
  )
)
with check (
  driver_id = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'driver'
  )
);

create policy "Drivers can delete own availability slots" on public.driver_availability_slots for delete
using (
  driver_id = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'driver'
  )
);

create policy "Admins can view all availability slots" on public.driver_availability_slots for select
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
);

alter table public.drivers_profiles enable row level security;

revoke insert on public.drivers_profiles from authenticated;
revoke update on public.drivers_profiles from authenticated;

grant insert (id, current_lat, current_lng, is_available, current_zone, updated_at)
  on public.drivers_profiles to authenticated;
grant update (current_lat, current_lng, is_available, current_zone, updated_at)
  on public.drivers_profiles to authenticated;

drop policy if exists "Drivers can insert own driver profile" on public.drivers_profiles;
drop policy if exists "Drivers can update own driver profile" on public.drivers_profiles;

create policy "Drivers can update own driver profile" on public.drivers_profiles for update
using (
  id = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'driver'
  )
)
with check (
  id = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'driver'
  )
);

create policy "Drivers can insert own driver profile" on public.drivers_profiles for insert
with check (
  id = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'driver'
  )
);
