create table if not exists public.restaurant_zone_pricing (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.profiles(id) on delete cascade,
  zone_id bigint not null references public.zones(id) on delete cascade,
  delivery_fee numeric not null default 0.0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (restaurant_id, zone_id)
);

alter table public.restaurant_zone_pricing enable row level security;

drop policy if exists "Admins can manage restaurant zone pricing" on public.restaurant_zone_pricing;
create policy "Admins can manage restaurant zone pricing" on public.restaurant_zone_pricing
for all
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
  )
);

drop policy if exists "Restaurants can view own zone pricing" on public.restaurant_zone_pricing;
create policy "Restaurants can view own zone pricing" on public.restaurant_zone_pricing
for select
using (restaurant_id = auth.uid());

drop policy if exists "Restaurants can view assigned zones" on public.zones;
create policy "Restaurants can view assigned zones" on public.zones
for select
using (
  exists (
    select 1
    from public.restaurant_zone_pricing rzp
    where rzp.zone_id = zones.id
      and rzp.restaurant_id = auth.uid()
  )
);

grant select, insert, update, delete on public.restaurant_zone_pricing to authenticated;

